### PR TITLE
Bump major version numbers

### PR DESCRIPTION
**Pull request by kmicklas**
Breaking changes in `beam-core`: #413 (unlikely to break anyone in practice).

Breaking changes in `beam-migrate`: #329.

Breaking changes in `beam-postgres`: #329, #347 and associated PRs.

Breaking changes in `beam-sqlite`: #435.

### CODE REVIEW

**Comment by 3noch** [comment]
We need to update ChangeLogs too?

**Comment by kmicklas** [comment]
Yep, we need to do that before the release.

**Comment by kmicklas** [comment]
Hmm, the CI definitely didn't work on this. It succeeded without any output.

**Comment by kmicklas** [comment]
> Hmm, the CI definitely didn't work on this. It succeeded without any output.

Or not: https://github.com/kmicklas/beam/runs/755025866

Something very weird is up with the `pull_request` version, even though the `push` one correctly failed.

**Pull request merged**
