### PR TITLE
Version bound updates

### PR DESCRIPTION
**Pull request by LaurentRDC**
This is a small PR to loosen some version bounds

### CODE REVIEW

**Comment by LaurentRDC** [comment]
In related news, @kmicklas I would be happy to help maintain the beam repository and Hackage packages. [See here](https://hackage.haskell.org/user/LaurentRDC) for a list of other Haskell packages I maintain

**Comment by LaurentRDC** [comment]
@tathougies Would you be willing to let me help maintain this repository? See the comment above for other Haskell packages I maintain

**Comment by kmicklas** [comment]
@LaurentRDC I would definitely appreciate more help with maintainership; let's make sure @tathougies is on board since it's his project originally. :slightly_smiling_face:

**Comment by tathougies** [comment]
Yeah, I'm fine with that. Realistically, I have little to no time to work with beam (and Haskell in general) at this point. Thanks all for continuing maintenance! Glad people are still using it. I believe @kmicklas can add you directly (he should own the org as well).

**Comment by LaurentRDC** [comment]
@kmicklas Gentle ping to add me to the organization so I can help you!

**Comment by kmicklas** [comment]
> @kmicklas Gentle ping to add me to the organization and Hackage packages (username=LaurentRDC) so I can help you!

Hey sorry I am very busy the next few days but I will get to this on Tuesday!

**Pull request merged**
