### PR TITLE
Add tentative ChangeLog entries

### PR DESCRIPTION
**Pull request by kmicklas**
Rendered:

 * [beam-core](https://github.com/kmicklas/beam/blob/release-notes/beam-core/ChangeLog.md)
 * [beam-migrate](https://github.com/kmicklas/beam/blob/release-notes/beam-migrate/ChangeLog.md)
 * [beam-postgres](https://github.com/kmicklas/beam/blob/release-notes/beam-postgres/ChangeLog.md)
 * [beam-sqlite](https://github.com/kmicklas/beam/blob/release-notes/beam-sqlite/ChangeLog.md)

### CODE REVIEW

**Comment by tathougies** [comment]
I'm happy with this, although, let's get rid of the 'unreleased' portion. And then we can cut a GitHub release immediately afterwards, and upload to Hackage.

**Comment by tathougies** [comment]
can anyone say why the tests are failing? It seems to me they should work?
I think this is all good. Can we cut a release?

**Comment by kmicklas** [comment]
There seems to be some non-deterministic issue affecting Postgres startup. Maybe this would be fixed by #487?

```
2020-09-14 19:09:28.453 UTC [1360] LOG:  listening on Unix socket "/build/postgres-data-0f7126cc42e5333f/.s.PGSQL.5432"
Completed waiting for postgres
2020-09-14 19:09:28.469 UTC [1362] LOG:  database system was shut down at 2020-09-14 19:09:27 UTC
2020-09-14 19:09:28.472 UTC [1360] LOG:  database system is ready to accept connections
2020-09-14 19:09:28.473 UTC [1363] FATAL:  the database system is starting up
FAIL
      Exception: libpq: failed (FATAL:  the database system is starting up
```

**Comment by tathougies** [comment]
I think we can merge this?

**Pull request merged**
