### PR TITLE
Implement SQL features in beam-sqlite.

### PR DESCRIPTION
**Pull request by amano-kenji**
* T152, T152 // IS (NOT) DISTINCT FROM
* FULL OUTER JOIN
* SQL2003 Null Ordering
* Common Table Expression
* Window functions
* Filter clause // `FILTER (WHERE ...)`

It closes https://github.com/haskell-beam/beam/issues/648

### CODE REVIEW

**Comment by amano-kenji** [comment]
I request merging this pull request as soon as possible. An application I want to implement may depend on this pull request.

**Comment by amano-kenji** [comment]
By the way, I don't know whether distinctE for IsSql99ExpressionSyntax is correct. I copied distinctE from beam-postgres. `DISTINCT(select syntax)` doesn't feel correct for sqlite.

**Comment by amano-kenji** [comment]
* `uniqueE` is already implemented in beam-sqlite and beam-postgresql, and `WHERE UNIQUE (subquery)` is not supported by postgresql and sqlite.
* `distinctE` is already implemented in beam-postgresql, and `WHERE DISTINCT (subquery)` is not supported by postgresql and sqlite.
* If I just omit the implementation of similarTo, then I get compiler warnings. If you suggest any way to omit typeclass functions without getting compiler warnings, I will happily remove them.

Compiler warnings really bother me.

**Comment by tathougies** [comment]
So these are SQL standards you're implementing?

**Comment by amano-kenji** [comment]
After reading `warning: [-Wmissing-methods]`, I figured out that adding `-Wno-missing-methods` to `{-# OPTIONS_GHC #-}` block at the top suppresses missing methods warning in the whole file.

Are you okay with removing `distinctE` and `similarToE` and adding `-Wno-missing-methods` to `{-# OPTIONS_GHC #-}` block at the top of Syntax.hs?

**Comment by amano-kenji** [comment]
I figured out a way to remove `distinctE` and `similarToE` without getting a compiler warning.

It was to add `-Wno-missing-methods` to `{-# OPTIONS_GHC #-}`.

Now, my pull request doesn't implement anything not supported by SQLite. Is it ready to be merged?

**Comment by amano-kenji** [comment]
Can anyone at least take a look at this and respond? This pull request doesn't break existing codebases that depend on beam.

**Comment by tathougies** [comment]
I believe this is fine. I'm happy with it.

**Comment by amano-kenji** [comment]
Great.

**Comment by thomasjm** [comment]
This looks great to me and I'd love to see it merged! Maybe some tests would help provide confidence?

CC @kmicklas ?

**Comment by amano-kenji** [comment]
I accidentally removed my beam repository along with other repositories....

How can I recover this?

**Pull request closed without merging**
